--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/12/25 星期一 14:13:22
-- Server version: 5.7.12-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

-- 
-- Set default database
--
USE ip_get;

--
-- Definition for table ip_address
--
DROP TABLE IF EXISTS ip_address;
CREATE TABLE ip_address (
  id INT(20) NOT NULL AUTO_INCREMENT,
  ip VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'ip地址',
  port INT(5) NOT NULL DEFAULT 80 COMMENT '端口号',
  anonymity VARCHAR(20) NOT NULL DEFAULT '' COMMENT '匿名度',
  type VARCHAR(10) NOT NULL DEFAULT '' COMMENT '类型',
  location VARCHAR(100) NOT NULL DEFAULT '' COMMENT '位置',
  speed VARCHAR(15) NOT NULL DEFAULT '' COMMENT '相应速度',
  validate_time DATETIME DEFAULT NULL COMMENT '最后验证时间',
  PRIMARY KEY (id),
  UNIQUE INDEX ip_unique (ip)
)
ENGINE = INNODB
AUTO_INCREMENT = 16
AVG_ROW_LENGTH = 1170
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table ip_address
--
INSERT INTO ip_address VALUES
(1, '61.145.194.28', 8080, '高匿名', 'HTTP', '中国 广东省 东莞市 电信', '0.6秒', '2017-12-25 13:31:02'),
(2, '121.232.145.120', 9000, '高匿名', 'HTTP', '中国 江苏省 镇江市 电信', '3秒', '2017-12-25 12:30:55'),
(3, '119.5.0.52', 22, '高匿名', 'HTTP', '中国 四川省 南充市 联通', '1秒', '2017-12-25 11:30:46'),
(4, '119.5.0.20', 22, '高匿名', 'HTTP', '中国 四川省 南充市 联通', '3秒', '2017-12-25 10:28:33'),
(5, '180.118.128.247', 9000, '高匿名', 'HTTP', '中国 江苏省 镇江市 电信', '2秒', '2017-12-25 09:29:42'),
(6, '119.5.1.17', 22, '高匿名', 'HTTP', '中国 四川省 南充市 联通', '2秒', '2017-12-25 08:30:36'),
(7, '118.193.107.80', 80, '高匿名', 'HTTP', '中国 北京市 北京市 电信', '0.9秒', '2017-12-25 07:30:47'),
(8, '221.4.133.67', 53281, '高匿名', 'HTTP', '中国 广东省 东莞市 联通', '0.4秒', '2017-12-25 06:30:42'),
(9, '119.5.0.42', 22, '高匿名', 'HTTP', '中国 四川省 南充市 联通', '3秒', '2017-12-25 05:30:57'),
(10, '121.232.147.143', 9000, '高匿名', 'HTTP', '中国 江苏省 镇江市 电信', '1秒', '2017-12-25 04:30:24'),
(11, '223.223.187.195', 80, '高匿名', 'HTTP', '中国 北京市 北京市', '0.9秒', '2017-12-25 03:30:35'),
(12, '119.167.153.50', 8118, '高匿名', 'HTTP', '中国 山东省 青岛市 联通', '3秒', '2017-12-25 02:30:41'),
(13, '118.193.107.28', 80, '高匿名', 'HTTP', '中国 北京市 北京市 电信', '1秒', '2017-12-25 00:30:59'),
(14, '59.110.242.51', 8118, '高匿名', 'HTTP', '中国 北京市 北京市 阿里云', '3秒', '2017-12-24 23:30:52');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;